service: configs
owner: he110
description: Сервис централизованной конфигурации
type: business
organization: stream-gpt
port: 8080
env:
    HEALTH_CHECK_ENABLED: true
    LOG_LEVEL: info
    METRICS_ENABLED: true
env.staging:
    LOG_LEVEL: debug
env.production:
    LOG_LEVEL: warn

healthCheck:
  path: /health

dependencies:
  - type: database
    name: postgres
    version: 15
    database: configs_db
